version: '3'
 
services:
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    # ports:
    #   - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/init_db:/docker-entrypoint-initdb.d/:ro
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    ports:
      - 8081:80

  purepython:
    build:
      context: ./purepython
      target: final-islocaldevelopment-false
    environment:
      MYSQL_DATA_USER: admin
      MYSQL_DATA_PASSWORD: admin


volumes:
  dbdata: