name: snowcli
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies: 
  - python=3.10
  - snowflake-snowpark-python[pandas]=1.16.0
  - openssl=1.1.1
  - pip=23.3.1
  - ipykernel
  - pip:
      - snowflake-cli-labs==2.4.0